// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/flexible_grid_anchor_generator.proto

#include "object_detection/protos/flexible_grid_anchor_generator.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AnchorGrid_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto;
namespace object_detection {
namespace protos {
class FlexibleGridAnchorGeneratorDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FlexibleGridAnchorGenerator> _instance;
} _FlexibleGridAnchorGenerator_default_instance_;
class AnchorGridDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AnchorGrid> _instance;
} _AnchorGrid_default_instance_;
}  // namespace protos
}  // namespace object_detection
static void InitDefaultsscc_info_AnchorGrid_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::object_detection::protos::_AnchorGrid_default_instance_;
    new (ptr) ::object_detection::protos::AnchorGrid();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::object_detection::protos::AnchorGrid::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AnchorGrid_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_AnchorGrid_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto}, {}};

static void InitDefaultsscc_info_FlexibleGridAnchorGenerator_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::object_detection::protos::_FlexibleGridAnchorGenerator_default_instance_;
    new (ptr) ::object_detection::protos::FlexibleGridAnchorGenerator();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::object_detection::protos::FlexibleGridAnchorGenerator::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FlexibleGridAnchorGenerator_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsscc_info_FlexibleGridAnchorGenerator_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto}, {
      &scc_info_AnchorGrid_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::FlexibleGridAnchorGenerator, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::FlexibleGridAnchorGenerator, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::FlexibleGridAnchorGenerator, anchor_grid_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::FlexibleGridAnchorGenerator, normalize_coordinates_),
  ~0u,
  0,
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, base_sizes_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, aspect_ratios_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, height_stride_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, width_stride_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, height_offset_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::AnchorGrid, width_offset_),
  ~0u,
  ~0u,
  0,
  1,
  2,
  3,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::object_detection::protos::FlexibleGridAnchorGenerator)},
  { 9, 20, sizeof(::object_detection::protos::AnchorGrid)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::object_detection::protos::_FlexibleGridAnchorGenerator_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::object_detection::protos::_AnchorGrid_default_instance_),
};

const char descriptor_table_protodef_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n<object_detection/protos/flexible_grid_"
  "anchor_generator.proto\022\027object_detection"
  ".protos\"|\n\033FlexibleGridAnchorGenerator\0228"
  "\n\013anchor_grid\030\001 \003(\0132#.object_detection.p"
  "rotos.AnchorGrid\022#\n\025normalize_coordinate"
  "s\030\002 \001(\010:\004true\"\227\001\n\nAnchorGrid\022\022\n\nbase_siz"
  "es\030\001 \003(\002\022\025\n\raspect_ratios\030\002 \003(\002\022\025\n\rheigh"
  "t_stride\030\003 \001(\r\022\024\n\014width_stride\030\004 \001(\r\022\030\n\r"
  "height_offset\030\005 \001(\r:\0010\022\027\n\014width_offset\030\006"
  " \001(\r:\0010"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_sccs[2] = {
  &scc_info_AnchorGrid_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto.base,
  &scc_info_FlexibleGridAnchorGenerator_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_once;
static bool descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto = {
  &descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_initialized, descriptor_table_protodef_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto, "object_detection/protos/flexible_grid_anchor_generator.proto", 367,
  &descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_once, descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_sccs, descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto::offsets,
  file_level_metadata_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto, 2, file_level_enum_descriptors_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto, file_level_service_descriptors_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto), true);
namespace object_detection {
namespace protos {

// ===================================================================

void FlexibleGridAnchorGenerator::InitAsDefaultInstance() {
}
class FlexibleGridAnchorGenerator::_Internal {
 public:
  using HasBits = decltype(std::declval<FlexibleGridAnchorGenerator>()._has_bits_);
  static void set_has_normalize_coordinates(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

FlexibleGridAnchorGenerator::FlexibleGridAnchorGenerator()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:object_detection.protos.FlexibleGridAnchorGenerator)
}
FlexibleGridAnchorGenerator::FlexibleGridAnchorGenerator(const FlexibleGridAnchorGenerator& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      anchor_grid_(from.anchor_grid_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  normalize_coordinates_ = from.normalize_coordinates_;
  // @@protoc_insertion_point(copy_constructor:object_detection.protos.FlexibleGridAnchorGenerator)
}

void FlexibleGridAnchorGenerator::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FlexibleGridAnchorGenerator_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto.base);
  normalize_coordinates_ = true;
}

FlexibleGridAnchorGenerator::~FlexibleGridAnchorGenerator() {
  // @@protoc_insertion_point(destructor:object_detection.protos.FlexibleGridAnchorGenerator)
  SharedDtor();
}

void FlexibleGridAnchorGenerator::SharedDtor() {
}

void FlexibleGridAnchorGenerator::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FlexibleGridAnchorGenerator& FlexibleGridAnchorGenerator::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FlexibleGridAnchorGenerator_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto.base);
  return *internal_default_instance();
}


void FlexibleGridAnchorGenerator::Clear() {
// @@protoc_insertion_point(message_clear_start:object_detection.protos.FlexibleGridAnchorGenerator)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  anchor_grid_.Clear();
  normalize_coordinates_ = true;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* FlexibleGridAnchorGenerator::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .object_detection.protos.AnchorGrid anchor_grid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(add_anchor_grid(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 10);
        } else goto handle_unusual;
        continue;
      // optional bool normalize_coordinates = 2 [default = true];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_normalize_coordinates(&has_bits);
          normalize_coordinates_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool FlexibleGridAnchorGenerator::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:object_detection.protos.FlexibleGridAnchorGenerator)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .object_detection.protos.AnchorGrid anchor_grid = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
                input, add_anchor_grid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool normalize_coordinates = 2 [default = true];
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {
          _Internal::set_has_normalize_coordinates(&_has_bits_);
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   bool, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL>(
                 input, &normalize_coordinates_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:object_detection.protos.FlexibleGridAnchorGenerator)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:object_detection.protos.FlexibleGridAnchorGenerator)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void FlexibleGridAnchorGenerator::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:object_detection.protos.FlexibleGridAnchorGenerator)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .object_detection.protos.AnchorGrid anchor_grid = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->anchor_grid_size()); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->anchor_grid(static_cast<int>(i)),
      output);
  }

  cached_has_bits = _has_bits_[0];
  // optional bool normalize_coordinates = 2 [default = true];
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBool(2, this->normalize_coordinates(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:object_detection.protos.FlexibleGridAnchorGenerator)
}

::PROTOBUF_NAMESPACE_ID::uint8* FlexibleGridAnchorGenerator::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:object_detection.protos.FlexibleGridAnchorGenerator)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .object_detection.protos.AnchorGrid anchor_grid = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->anchor_grid_size()); i < n; i++) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->anchor_grid(static_cast<int>(i)), target);
  }

  cached_has_bits = _has_bits_[0];
  // optional bool normalize_coordinates = 2 [default = true];
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->normalize_coordinates(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:object_detection.protos.FlexibleGridAnchorGenerator)
  return target;
}

size_t FlexibleGridAnchorGenerator::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:object_detection.protos.FlexibleGridAnchorGenerator)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .object_detection.protos.AnchorGrid anchor_grid = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->anchor_grid_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          this->anchor_grid(static_cast<int>(i)));
    }
  }

  // optional bool normalize_coordinates = 2 [default = true];
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 1;
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FlexibleGridAnchorGenerator::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:object_detection.protos.FlexibleGridAnchorGenerator)
  GOOGLE_DCHECK_NE(&from, this);
  const FlexibleGridAnchorGenerator* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FlexibleGridAnchorGenerator>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:object_detection.protos.FlexibleGridAnchorGenerator)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:object_detection.protos.FlexibleGridAnchorGenerator)
    MergeFrom(*source);
  }
}

void FlexibleGridAnchorGenerator::MergeFrom(const FlexibleGridAnchorGenerator& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:object_detection.protos.FlexibleGridAnchorGenerator)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  anchor_grid_.MergeFrom(from.anchor_grid_);
  if (from.has_normalize_coordinates()) {
    set_normalize_coordinates(from.normalize_coordinates());
  }
}

void FlexibleGridAnchorGenerator::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:object_detection.protos.FlexibleGridAnchorGenerator)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlexibleGridAnchorGenerator::CopyFrom(const FlexibleGridAnchorGenerator& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:object_detection.protos.FlexibleGridAnchorGenerator)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlexibleGridAnchorGenerator::IsInitialized() const {
  return true;
}

void FlexibleGridAnchorGenerator::InternalSwap(FlexibleGridAnchorGenerator* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  CastToBase(&anchor_grid_)->InternalSwap(CastToBase(&other->anchor_grid_));
  swap(normalize_coordinates_, other->normalize_coordinates_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FlexibleGridAnchorGenerator::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AnchorGrid::InitAsDefaultInstance() {
}
class AnchorGrid::_Internal {
 public:
  using HasBits = decltype(std::declval<AnchorGrid>()._has_bits_);
  static void set_has_height_stride(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_width_stride(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_height_offset(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_width_offset(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

AnchorGrid::AnchorGrid()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:object_detection.protos.AnchorGrid)
}
AnchorGrid::AnchorGrid(const AnchorGrid& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      base_sizes_(from.base_sizes_),
      aspect_ratios_(from.aspect_ratios_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&height_stride_, &from.height_stride_,
    static_cast<size_t>(reinterpret_cast<char*>(&width_offset_) -
    reinterpret_cast<char*>(&height_stride_)) + sizeof(width_offset_));
  // @@protoc_insertion_point(copy_constructor:object_detection.protos.AnchorGrid)
}

void AnchorGrid::SharedCtor() {
  ::memset(&height_stride_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&width_offset_) -
      reinterpret_cast<char*>(&height_stride_)) + sizeof(width_offset_));
}

AnchorGrid::~AnchorGrid() {
  // @@protoc_insertion_point(destructor:object_detection.protos.AnchorGrid)
  SharedDtor();
}

void AnchorGrid::SharedDtor() {
}

void AnchorGrid::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AnchorGrid& AnchorGrid::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AnchorGrid_object_5fdetection_2fprotos_2fflexible_5fgrid_5fanchor_5fgenerator_2eproto.base);
  return *internal_default_instance();
}


void AnchorGrid::Clear() {
// @@protoc_insertion_point(message_clear_start:object_detection.protos.AnchorGrid)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  base_sizes_.Clear();
  aspect_ratios_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&height_stride_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&width_offset_) -
        reinterpret_cast<char*>(&height_stride_)) + sizeof(width_offset_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* AnchorGrid::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated float base_sizes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          ptr -= 1;
          do {
            ptr += 1;
            add_base_sizes(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
            ptr += sizeof(float);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 13);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(mutable_base_sizes(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated float aspect_ratios = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          ptr -= 1;
          do {
            ptr += 1;
            add_aspect_ratios(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
            ptr += sizeof(float);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 21);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(mutable_aspect_ratios(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 height_stride = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_height_stride(&has_bits);
          height_stride_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 width_stride = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_width_stride(&has_bits);
          width_stride_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 height_offset = 5 [default = 0];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_height_offset(&has_bits);
          height_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 width_offset = 6 [default = 0];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_width_offset(&has_bits);
          width_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool AnchorGrid::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:object_detection.protos.AnchorGrid)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float base_sizes = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (13 & 0xFF)) {
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 13u, input, this->mutable_base_sizes())));
        } else if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_base_sizes())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float aspect_ratios = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (21 & 0xFF)) {
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 21u, input, this->mutable_aspect_ratios())));
        } else if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_aspect_ratios())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 height_stride = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (24 & 0xFF)) {
          _Internal::set_has_height_stride(&_has_bits_);
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_stride_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 width_stride = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (32 & 0xFF)) {
          _Internal::set_has_width_stride(&_has_bits_);
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_stride_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 height_offset = 5 [default = 0];
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (40 & 0xFF)) {
          _Internal::set_has_height_offset(&_has_bits_);
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_offset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 width_offset = 6 [default = 0];
      case 6: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (48 & 0xFF)) {
          _Internal::set_has_width_offset(&_has_bits_);
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_offset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:object_detection.protos.AnchorGrid)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:object_detection.protos.AnchorGrid)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void AnchorGrid::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:object_detection.protos.AnchorGrid)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float base_sizes = 1;
  for (int i = 0, n = this->base_sizes_size(); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(
      1, this->base_sizes(i), output);
  }

  // repeated float aspect_ratios = 2;
  for (int i = 0, n = this->aspect_ratios_size(); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(
      2, this->aspect_ratios(i), output);
  }

  cached_has_bits = _has_bits_[0];
  // optional uint32 height_stride = 3;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32(3, this->height_stride(), output);
  }

  // optional uint32 width_stride = 4;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32(4, this->width_stride(), output);
  }

  // optional uint32 height_offset = 5 [default = 0];
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32(5, this->height_offset(), output);
  }

  // optional uint32 width_offset = 6 [default = 0];
  if (cached_has_bits & 0x00000008u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32(6, this->width_offset(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:object_detection.protos.AnchorGrid)
}

::PROTOBUF_NAMESPACE_ID::uint8* AnchorGrid::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:object_detection.protos.AnchorGrid)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float base_sizes = 1;
  target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
    WriteFloatToArray(1, this->base_sizes_, target);

  // repeated float aspect_ratios = 2;
  target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
    WriteFloatToArray(2, this->aspect_ratios_, target);

  cached_has_bits = _has_bits_[0];
  // optional uint32 height_stride = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->height_stride(), target);
  }

  // optional uint32 width_stride = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->width_stride(), target);
  }

  // optional uint32 height_offset = 5 [default = 0];
  if (cached_has_bits & 0x00000004u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->height_offset(), target);
  }

  // optional uint32 width_offset = 6 [default = 0];
  if (cached_has_bits & 0x00000008u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->width_offset(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:object_detection.protos.AnchorGrid)
  return target;
}

size_t AnchorGrid::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:object_detection.protos.AnchorGrid)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float base_sizes = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->base_sizes_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->base_sizes_size());
    total_size += data_size;
  }

  // repeated float aspect_ratios = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->aspect_ratios_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->aspect_ratios_size());
    total_size += data_size;
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional uint32 height_stride = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->height_stride());
    }

    // optional uint32 width_stride = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->width_stride());
    }

    // optional uint32 height_offset = 5 [default = 0];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->height_offset());
    }

    // optional uint32 width_offset = 6 [default = 0];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->width_offset());
    }

  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AnchorGrid::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:object_detection.protos.AnchorGrid)
  GOOGLE_DCHECK_NE(&from, this);
  const AnchorGrid* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AnchorGrid>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:object_detection.protos.AnchorGrid)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:object_detection.protos.AnchorGrid)
    MergeFrom(*source);
  }
}

void AnchorGrid::MergeFrom(const AnchorGrid& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:object_detection.protos.AnchorGrid)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  base_sizes_.MergeFrom(from.base_sizes_);
  aspect_ratios_.MergeFrom(from.aspect_ratios_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      height_stride_ = from.height_stride_;
    }
    if (cached_has_bits & 0x00000002u) {
      width_stride_ = from.width_stride_;
    }
    if (cached_has_bits & 0x00000004u) {
      height_offset_ = from.height_offset_;
    }
    if (cached_has_bits & 0x00000008u) {
      width_offset_ = from.width_offset_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void AnchorGrid::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:object_detection.protos.AnchorGrid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AnchorGrid::CopyFrom(const AnchorGrid& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:object_detection.protos.AnchorGrid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnchorGrid::IsInitialized() const {
  return true;
}

void AnchorGrid::InternalSwap(AnchorGrid* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  base_sizes_.InternalSwap(&other->base_sizes_);
  aspect_ratios_.InternalSwap(&other->aspect_ratios_);
  swap(height_stride_, other->height_stride_);
  swap(width_stride_, other->width_stride_);
  swap(height_offset_, other->height_offset_);
  swap(width_offset_, other->width_offset_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AnchorGrid::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::object_detection::protos::FlexibleGridAnchorGenerator* Arena::CreateMaybeMessage< ::object_detection::protos::FlexibleGridAnchorGenerator >(Arena* arena) {
  return Arena::CreateInternal< ::object_detection::protos::FlexibleGridAnchorGenerator >(arena);
}
template<> PROTOBUF_NOINLINE ::object_detection::protos::AnchorGrid* Arena::CreateMaybeMessage< ::object_detection::protos::AnchorGrid >(Arena* arena) {
  return Arena::CreateInternal< ::object_detection::protos::AnchorGrid >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
