// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/model.proto

#include "object_detection/protos/model.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<8> scc_info_FasterRcnn_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2fssd_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<10> scc_info_Ssd_object_5fdetection_2fprotos_2fssd_2eproto;
namespace object_detection {
namespace protos {
class DetectionModelDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DetectionModel> _instance;
  const ::object_detection::protos::FasterRcnn* faster_rcnn_;
  const ::object_detection::protos::Ssd* ssd_;
} _DetectionModel_default_instance_;
}  // namespace protos
}  // namespace object_detection
static void InitDefaultsscc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::object_detection::protos::_DetectionModel_default_instance_;
    new (ptr) ::object_detection::protos::DetectionModel();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::object_detection::protos::DetectionModel::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsscc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto}, {
      &scc_info_FasterRcnn_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto.base,
      &scc_info_Ssd_object_5fdetection_2fprotos_2fssd_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_object_5fdetection_2fprotos_2fmodel_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_object_5fdetection_2fprotos_2fmodel_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_object_5fdetection_2fprotos_2fmodel_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_object_5fdetection_2fprotos_2fmodel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::DetectionModel, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::DetectionModel, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::DetectionModel, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::object_detection::protos::DetectionModelDefaultTypeInternal, faster_rcnn_),
  offsetof(::object_detection::protos::DetectionModelDefaultTypeInternal, ssd_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::DetectionModel, model_),
  ~0u,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::object_detection::protos::DetectionModel)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::object_detection::protos::_DetectionModel_default_instance_),
};

const char descriptor_table_protodef_object_5fdetection_2fprotos_2fmodel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n#object_detection/protos/model.proto\022\027o"
  "bject_detection.protos\032)object_detection"
  "/protos/faster_rcnn.proto\032!object_detect"
  "ion/protos/ssd.proto\"\202\001\n\016DetectionModel\022"
  ":\n\013faster_rcnn\030\001 \001(\0132#.object_detection."
  "protos.FasterRcnnH\000\022+\n\003ssd\030\002 \001(\0132\034.objec"
  "t_detection.protos.SsdH\000B\007\n\005model"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_deps[2] = {
  &::descriptor_table_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto,
  &::descriptor_table_object_5fdetection_2fprotos_2fssd_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_sccs[1] = {
  &scc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_once;
static bool descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto = {
  &descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_initialized, descriptor_table_protodef_object_5fdetection_2fprotos_2fmodel_2eproto, "object_detection/protos/model.proto", 273,
  &descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_once, descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_sccs, descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_object_5fdetection_2fprotos_2fmodel_2eproto::offsets,
  file_level_metadata_object_5fdetection_2fprotos_2fmodel_2eproto, 1, file_level_enum_descriptors_object_5fdetection_2fprotos_2fmodel_2eproto, file_level_service_descriptors_object_5fdetection_2fprotos_2fmodel_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_object_5fdetection_2fprotos_2fmodel_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto), true);
namespace object_detection {
namespace protos {

// ===================================================================

void DetectionModel::InitAsDefaultInstance() {
  ::object_detection::protos::_DetectionModel_default_instance_.faster_rcnn_ = const_cast< ::object_detection::protos::FasterRcnn*>(
      ::object_detection::protos::FasterRcnn::internal_default_instance());
  ::object_detection::protos::_DetectionModel_default_instance_.ssd_ = const_cast< ::object_detection::protos::Ssd*>(
      ::object_detection::protos::Ssd::internal_default_instance());
}
class DetectionModel::_Internal {
 public:
  using HasBits = decltype(std::declval<DetectionModel>()._has_bits_);
  static const ::object_detection::protos::FasterRcnn& faster_rcnn(const DetectionModel* msg);
  static const ::object_detection::protos::Ssd& ssd(const DetectionModel* msg);
};

const ::object_detection::protos::FasterRcnn&
DetectionModel::_Internal::faster_rcnn(const DetectionModel* msg) {
  return *msg->model_.faster_rcnn_;
}
const ::object_detection::protos::Ssd&
DetectionModel::_Internal::ssd(const DetectionModel* msg) {
  return *msg->model_.ssd_;
}
void DetectionModel::set_allocated_faster_rcnn(::object_detection::protos::FasterRcnn* faster_rcnn) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_model();
  if (faster_rcnn) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      faster_rcnn = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, faster_rcnn, submessage_arena);
    }
    set_has_faster_rcnn();
    model_.faster_rcnn_ = faster_rcnn;
  }
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.DetectionModel.faster_rcnn)
}
void DetectionModel::clear_faster_rcnn() {
  if (has_faster_rcnn()) {
    delete model_.faster_rcnn_;
    clear_has_model();
  }
}
void DetectionModel::set_allocated_ssd(::object_detection::protos::Ssd* ssd) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_model();
  if (ssd) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      ssd = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ssd, submessage_arena);
    }
    set_has_ssd();
    model_.ssd_ = ssd;
  }
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.DetectionModel.ssd)
}
void DetectionModel::clear_ssd() {
  if (has_ssd()) {
    delete model_.ssd_;
    clear_has_model();
  }
}
DetectionModel::DetectionModel()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:object_detection.protos.DetectionModel)
}
DetectionModel::DetectionModel(const DetectionModel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_model();
  switch (from.model_case()) {
    case kFasterRcnn: {
      mutable_faster_rcnn()->::object_detection::protos::FasterRcnn::MergeFrom(from.faster_rcnn());
      break;
    }
    case kSsd: {
      mutable_ssd()->::object_detection::protos::Ssd::MergeFrom(from.ssd());
      break;
    }
    case MODEL_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:object_detection.protos.DetectionModel)
}

void DetectionModel::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto.base);
  clear_has_model();
}

DetectionModel::~DetectionModel() {
  // @@protoc_insertion_point(destructor:object_detection.protos.DetectionModel)
  SharedDtor();
}

void DetectionModel::SharedDtor() {
  if (has_model()) {
    clear_model();
  }
}

void DetectionModel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DetectionModel& DetectionModel::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto.base);
  return *internal_default_instance();
}


void DetectionModel::clear_model() {
// @@protoc_insertion_point(one_of_clear_start:object_detection.protos.DetectionModel)
  switch (model_case()) {
    case kFasterRcnn: {
      delete model_.faster_rcnn_;
      break;
    }
    case kSsd: {
      delete model_.ssd_;
      break;
    }
    case MODEL_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MODEL_NOT_SET;
}


void DetectionModel::Clear() {
// @@protoc_insertion_point(message_clear_start:object_detection.protos.DetectionModel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_model();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DetectionModel::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .object_detection.protos.FasterRcnn faster_rcnn = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(mutable_faster_rcnn(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .object_detection.protos.Ssd ssd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(mutable_ssd(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DetectionModel::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:object_detection.protos.DetectionModel)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .object_detection.protos.FasterRcnn faster_rcnn = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_faster_rcnn()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .object_detection.protos.Ssd ssd = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_ssd()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:object_detection.protos.DetectionModel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:object_detection.protos.DetectionModel)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DetectionModel::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:object_detection.protos.DetectionModel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (model_case()) {
    case kFasterRcnn:
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
        1, _Internal::faster_rcnn(this), output);
      break;
    case kSsd:
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
        2, _Internal::ssd(this), output);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:object_detection.protos.DetectionModel)
}

::PROTOBUF_NAMESPACE_ID::uint8* DetectionModel::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:object_detection.protos.DetectionModel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (model_case()) {
    case kFasterRcnn:
      target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessageToArray(
          1, _Internal::faster_rcnn(this), target);
      break;
    case kSsd:
      target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessageToArray(
          2, _Internal::ssd(this), target);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:object_detection.protos.DetectionModel)
  return target;
}

size_t DetectionModel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:object_detection.protos.DetectionModel)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (model_case()) {
    // optional .object_detection.protos.FasterRcnn faster_rcnn = 1;
    case kFasterRcnn: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *model_.faster_rcnn_);
      break;
    }
    // optional .object_detection.protos.Ssd ssd = 2;
    case kSsd: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *model_.ssd_);
      break;
    }
    case MODEL_NOT_SET: {
      break;
    }
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DetectionModel::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:object_detection.protos.DetectionModel)
  GOOGLE_DCHECK_NE(&from, this);
  const DetectionModel* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DetectionModel>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:object_detection.protos.DetectionModel)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:object_detection.protos.DetectionModel)
    MergeFrom(*source);
  }
}

void DetectionModel::MergeFrom(const DetectionModel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:object_detection.protos.DetectionModel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.model_case()) {
    case kFasterRcnn: {
      mutable_faster_rcnn()->::object_detection::protos::FasterRcnn::MergeFrom(from.faster_rcnn());
      break;
    }
    case kSsd: {
      mutable_ssd()->::object_detection::protos::Ssd::MergeFrom(from.ssd());
      break;
    }
    case MODEL_NOT_SET: {
      break;
    }
  }
}

void DetectionModel::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:object_detection.protos.DetectionModel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DetectionModel::CopyFrom(const DetectionModel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:object_detection.protos.DetectionModel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectionModel::IsInitialized() const {
  return true;
}

void DetectionModel::InternalSwap(DetectionModel* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(model_, other->model_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata DetectionModel::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::object_detection::protos::DetectionModel* Arena::CreateMaybeMessage< ::object_detection::protos::DetectionModel >(Arena* arena) {
  return Arena::CreateInternal< ::object_detection::protos::DetectionModel >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
