// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/pipeline.proto

#include "object_detection/protos/pipeline.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2fmodel_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2feval_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EvalConfig_object_5fdetection_2fprotos_2feval_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2fgraph_5frewriter_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GraphRewriter_object_5fdetection_2fprotos_2fgraph_5frewriter_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2finput_5freader_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_InputReader_object_5fdetection_2fprotos_2finput_5freader_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2ftrain_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_TrainConfig_object_5fdetection_2fprotos_2ftrain_2eproto;
namespace object_detection {
namespace protos {
class TrainEvalPipelineConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TrainEvalPipelineConfig> _instance;
} _TrainEvalPipelineConfig_default_instance_;
}  // namespace protos
}  // namespace object_detection
static void InitDefaultsscc_info_TrainEvalPipelineConfig_object_5fdetection_2fprotos_2fpipeline_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::object_detection::protos::_TrainEvalPipelineConfig_default_instance_;
    new (ptr) ::object_detection::protos::TrainEvalPipelineConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::object_detection::protos::TrainEvalPipelineConfig::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<5> scc_info_TrainEvalPipelineConfig_object_5fdetection_2fprotos_2fpipeline_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 5, InitDefaultsscc_info_TrainEvalPipelineConfig_object_5fdetection_2fprotos_2fpipeline_2eproto}, {
      &scc_info_DetectionModel_object_5fdetection_2fprotos_2fmodel_2eproto.base,
      &scc_info_TrainConfig_object_5fdetection_2fprotos_2ftrain_2eproto.base,
      &scc_info_InputReader_object_5fdetection_2fprotos_2finput_5freader_2eproto.base,
      &scc_info_EvalConfig_object_5fdetection_2fprotos_2feval_2eproto.base,
      &scc_info_GraphRewriter_object_5fdetection_2fprotos_2fgraph_5frewriter_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_object_5fdetection_2fprotos_2fpipeline_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_object_5fdetection_2fprotos_2fpipeline_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_object_5fdetection_2fprotos_2fpipeline_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_object_5fdetection_2fprotos_2fpipeline_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, _internal_metadata_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, _extensions_),
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, model_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, train_config_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, train_input_reader_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, eval_config_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, eval_input_reader_),
  PROTOBUF_FIELD_OFFSET(::object_detection::protos::TrainEvalPipelineConfig, graph_rewriter_),
  0,
  1,
  2,
  3,
  ~0u,
  4,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(::object_detection::protos::TrainEvalPipelineConfig)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::object_detection::protos::_TrainEvalPipelineConfig_default_instance_),
};

const char descriptor_table_protodef_object_5fdetection_2fprotos_2fpipeline_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&object_detection/protos/pipeline.proto"
  "\022\027object_detection.protos\032\"object_detect"
  "ion/protos/eval.proto\032,object_detection/"
  "protos/graph_rewriter.proto\032*object_dete"
  "ction/protos/input_reader.proto\032#object_"
  "detection/protos/model.proto\032#object_det"
  "ection/protos/train.proto\"\225\003\n\027TrainEvalP"
  "ipelineConfig\0226\n\005model\030\001 \001(\0132\'.object_de"
  "tection.protos.DetectionModel\022:\n\014train_c"
  "onfig\030\002 \001(\0132$.object_detection.protos.Tr"
  "ainConfig\022@\n\022train_input_reader\030\003 \001(\0132$."
  "object_detection.protos.InputReader\0228\n\013e"
  "val_config\030\004 \001(\0132#.object_detection.prot"
  "os.EvalConfig\022\?\n\021eval_input_reader\030\005 \003(\013"
  "2$.object_detection.protos.InputReader\022>"
  "\n\016graph_rewriter\030\006 \001(\0132&.object_detectio"
  "n.protos.GraphRewriter*\t\010\350\007\020\200\200\200\200\002"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_deps[5] = {
  &::descriptor_table_object_5fdetection_2fprotos_2feval_2eproto,
  &::descriptor_table_object_5fdetection_2fprotos_2fgraph_5frewriter_2eproto,
  &::descriptor_table_object_5fdetection_2fprotos_2finput_5freader_2eproto,
  &::descriptor_table_object_5fdetection_2fprotos_2fmodel_2eproto,
  &::descriptor_table_object_5fdetection_2fprotos_2ftrain_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_sccs[1] = {
  &scc_info_TrainEvalPipelineConfig_object_5fdetection_2fprotos_2fpipeline_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_once;
static bool descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto = {
  &descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_initialized, descriptor_table_protodef_object_5fdetection_2fprotos_2fpipeline_2eproto, "object_detection/protos/pipeline.proto", 673,
  &descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_once, descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_sccs, descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto_deps, 1, 5,
  schemas, file_default_instances, TableStruct_object_5fdetection_2fprotos_2fpipeline_2eproto::offsets,
  file_level_metadata_object_5fdetection_2fprotos_2fpipeline_2eproto, 1, file_level_enum_descriptors_object_5fdetection_2fprotos_2fpipeline_2eproto, file_level_service_descriptors_object_5fdetection_2fprotos_2fpipeline_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_object_5fdetection_2fprotos_2fpipeline_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_object_5fdetection_2fprotos_2fpipeline_2eproto), true);
namespace object_detection {
namespace protos {

// ===================================================================

void TrainEvalPipelineConfig::InitAsDefaultInstance() {
  ::object_detection::protos::_TrainEvalPipelineConfig_default_instance_._instance.get_mutable()->model_ = const_cast< ::object_detection::protos::DetectionModel*>(
      ::object_detection::protos::DetectionModel::internal_default_instance());
  ::object_detection::protos::_TrainEvalPipelineConfig_default_instance_._instance.get_mutable()->train_config_ = const_cast< ::object_detection::protos::TrainConfig*>(
      ::object_detection::protos::TrainConfig::internal_default_instance());
  ::object_detection::protos::_TrainEvalPipelineConfig_default_instance_._instance.get_mutable()->train_input_reader_ = const_cast< ::object_detection::protos::InputReader*>(
      ::object_detection::protos::InputReader::internal_default_instance());
  ::object_detection::protos::_TrainEvalPipelineConfig_default_instance_._instance.get_mutable()->eval_config_ = const_cast< ::object_detection::protos::EvalConfig*>(
      ::object_detection::protos::EvalConfig::internal_default_instance());
  ::object_detection::protos::_TrainEvalPipelineConfig_default_instance_._instance.get_mutable()->graph_rewriter_ = const_cast< ::object_detection::protos::GraphRewriter*>(
      ::object_detection::protos::GraphRewriter::internal_default_instance());
}
class TrainEvalPipelineConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<TrainEvalPipelineConfig>()._has_bits_);
  static const ::object_detection::protos::DetectionModel& model(const TrainEvalPipelineConfig* msg);
  static void set_has_model(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::object_detection::protos::TrainConfig& train_config(const TrainEvalPipelineConfig* msg);
  static void set_has_train_config(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::object_detection::protos::InputReader& train_input_reader(const TrainEvalPipelineConfig* msg);
  static void set_has_train_input_reader(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::object_detection::protos::EvalConfig& eval_config(const TrainEvalPipelineConfig* msg);
  static void set_has_eval_config(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::object_detection::protos::GraphRewriter& graph_rewriter(const TrainEvalPipelineConfig* msg);
  static void set_has_graph_rewriter(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

const ::object_detection::protos::DetectionModel&
TrainEvalPipelineConfig::_Internal::model(const TrainEvalPipelineConfig* msg) {
  return *msg->model_;
}
const ::object_detection::protos::TrainConfig&
TrainEvalPipelineConfig::_Internal::train_config(const TrainEvalPipelineConfig* msg) {
  return *msg->train_config_;
}
const ::object_detection::protos::InputReader&
TrainEvalPipelineConfig::_Internal::train_input_reader(const TrainEvalPipelineConfig* msg) {
  return *msg->train_input_reader_;
}
const ::object_detection::protos::EvalConfig&
TrainEvalPipelineConfig::_Internal::eval_config(const TrainEvalPipelineConfig* msg) {
  return *msg->eval_config_;
}
const ::object_detection::protos::GraphRewriter&
TrainEvalPipelineConfig::_Internal::graph_rewriter(const TrainEvalPipelineConfig* msg) {
  return *msg->graph_rewriter_;
}
void TrainEvalPipelineConfig::clear_model() {
  if (model_ != nullptr) model_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void TrainEvalPipelineConfig::clear_train_config() {
  if (train_config_ != nullptr) train_config_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void TrainEvalPipelineConfig::clear_train_input_reader() {
  if (train_input_reader_ != nullptr) train_input_reader_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
void TrainEvalPipelineConfig::clear_eval_config() {
  if (eval_config_ != nullptr) eval_config_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
void TrainEvalPipelineConfig::clear_eval_input_reader() {
  eval_input_reader_.Clear();
}
void TrainEvalPipelineConfig::clear_graph_rewriter() {
  if (graph_rewriter_ != nullptr) graph_rewriter_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
TrainEvalPipelineConfig::TrainEvalPipelineConfig()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:object_detection.protos.TrainEvalPipelineConfig)
}
TrainEvalPipelineConfig::TrainEvalPipelineConfig(const TrainEvalPipelineConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      eval_input_reader_(from.eval_input_reader_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _extensions_.MergeFrom(from._extensions_);
  if (from.has_model()) {
    model_ = new ::object_detection::protos::DetectionModel(*from.model_);
  } else {
    model_ = nullptr;
  }
  if (from.has_train_config()) {
    train_config_ = new ::object_detection::protos::TrainConfig(*from.train_config_);
  } else {
    train_config_ = nullptr;
  }
  if (from.has_train_input_reader()) {
    train_input_reader_ = new ::object_detection::protos::InputReader(*from.train_input_reader_);
  } else {
    train_input_reader_ = nullptr;
  }
  if (from.has_eval_config()) {
    eval_config_ = new ::object_detection::protos::EvalConfig(*from.eval_config_);
  } else {
    eval_config_ = nullptr;
  }
  if (from.has_graph_rewriter()) {
    graph_rewriter_ = new ::object_detection::protos::GraphRewriter(*from.graph_rewriter_);
  } else {
    graph_rewriter_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:object_detection.protos.TrainEvalPipelineConfig)
}

void TrainEvalPipelineConfig::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TrainEvalPipelineConfig_object_5fdetection_2fprotos_2fpipeline_2eproto.base);
  ::memset(&model_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&graph_rewriter_) -
      reinterpret_cast<char*>(&model_)) + sizeof(graph_rewriter_));
}

TrainEvalPipelineConfig::~TrainEvalPipelineConfig() {
  // @@protoc_insertion_point(destructor:object_detection.protos.TrainEvalPipelineConfig)
  SharedDtor();
}

void TrainEvalPipelineConfig::SharedDtor() {
  if (this != internal_default_instance()) delete model_;
  if (this != internal_default_instance()) delete train_config_;
  if (this != internal_default_instance()) delete train_input_reader_;
  if (this != internal_default_instance()) delete eval_config_;
  if (this != internal_default_instance()) delete graph_rewriter_;
}

void TrainEvalPipelineConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TrainEvalPipelineConfig& TrainEvalPipelineConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TrainEvalPipelineConfig_object_5fdetection_2fprotos_2fpipeline_2eproto.base);
  return *internal_default_instance();
}


void TrainEvalPipelineConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:object_detection.protos.TrainEvalPipelineConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _extensions_.Clear();
  eval_input_reader_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(model_ != nullptr);
      model_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(train_config_ != nullptr);
      train_config_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(train_input_reader_ != nullptr);
      train_input_reader_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(eval_config_ != nullptr);
      eval_config_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(graph_rewriter_ != nullptr);
      graph_rewriter_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TrainEvalPipelineConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .object_detection.protos.DetectionModel model = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(mutable_model(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .object_detection.protos.TrainConfig train_config = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(mutable_train_config(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .object_detection.protos.InputReader train_input_reader = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(mutable_train_input_reader(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .object_detection.protos.EvalConfig eval_config = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(mutable_eval_config(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .object_detection.protos.InputReader eval_input_reader = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(add_eval_input_reader(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 42);
        } else goto handle_unusual;
        continue;
      // optional .object_detection.protos.GraphRewriter graph_rewriter = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(mutable_graph_rewriter(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
      if ((8000u <= tag)) {
        ptr = _extensions_.ParseField(tag, ptr,
            internal_default_instance(), &_internal_metadata_, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TrainEvalPipelineConfig::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:object_detection.protos.TrainEvalPipelineConfig)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .object_detection.protos.DetectionModel model = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_model()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .object_detection.protos.TrainConfig train_config = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_train_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .object_detection.protos.InputReader train_input_reader = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_train_input_reader()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .object_detection.protos.EvalConfig eval_config = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_eval_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .object_detection.protos.InputReader eval_input_reader = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (42 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
                input, add_eval_input_reader()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .object_detection.protos.GraphRewriter graph_rewriter = 6;
      case 6: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (50 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_graph_rewriter()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        if ((8000u <= tag)) {
          DO_(_extensions_.ParseField(tag, input,
              internal_default_instance(),
              _internal_metadata_.mutable_unknown_fields()));
          continue;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:object_detection.protos.TrainEvalPipelineConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:object_detection.protos.TrainEvalPipelineConfig)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TrainEvalPipelineConfig::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:object_detection.protos.TrainEvalPipelineConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .object_detection.protos.DetectionModel model = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, _Internal::model(this), output);
  }

  // optional .object_detection.protos.TrainConfig train_config = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, _Internal::train_config(this), output);
  }

  // optional .object_detection.protos.InputReader train_input_reader = 3;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, _Internal::train_input_reader(this), output);
  }

  // optional .object_detection.protos.EvalConfig eval_config = 4;
  if (cached_has_bits & 0x00000008u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, _Internal::eval_config(this), output);
  }

  // repeated .object_detection.protos.InputReader eval_input_reader = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->eval_input_reader_size()); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->eval_input_reader(static_cast<int>(i)),
      output);
  }

  // optional .object_detection.protos.GraphRewriter graph_rewriter = 6;
  if (cached_has_bits & 0x00000010u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, _Internal::graph_rewriter(this), output);
  }

  // Extension range [1000, 536870912)
  _extensions_.SerializeWithCachedSizes(1000, 536870912, output);

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:object_detection.protos.TrainEvalPipelineConfig)
}

::PROTOBUF_NAMESPACE_ID::uint8* TrainEvalPipelineConfig::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:object_detection.protos.TrainEvalPipelineConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .object_detection.protos.DetectionModel model = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::model(this), target);
  }

  // optional .object_detection.protos.TrainConfig train_config = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, _Internal::train_config(this), target);
  }

  // optional .object_detection.protos.InputReader train_input_reader = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, _Internal::train_input_reader(this), target);
  }

  // optional .object_detection.protos.EvalConfig eval_config = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, _Internal::eval_config(this), target);
  }

  // repeated .object_detection.protos.InputReader eval_input_reader = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->eval_input_reader_size()); i < n; i++) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->eval_input_reader(static_cast<int>(i)), target);
  }

  // optional .object_detection.protos.GraphRewriter graph_rewriter = 6;
  if (cached_has_bits & 0x00000010u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, _Internal::graph_rewriter(this), target);
  }

  // Extension range [1000, 536870912)
  target = _extensions_.InternalSerializeWithCachedSizesToArray(
      1000, 536870912, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:object_detection.protos.TrainEvalPipelineConfig)
  return target;
}

size_t TrainEvalPipelineConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:object_detection.protos.TrainEvalPipelineConfig)
  size_t total_size = 0;

  total_size += _extensions_.ByteSize();

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .object_detection.protos.InputReader eval_input_reader = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->eval_input_reader_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          this->eval_input_reader(static_cast<int>(i)));
    }
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional .object_detection.protos.DetectionModel model = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *model_);
    }

    // optional .object_detection.protos.TrainConfig train_config = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *train_config_);
    }

    // optional .object_detection.protos.InputReader train_input_reader = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *train_input_reader_);
    }

    // optional .object_detection.protos.EvalConfig eval_config = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *eval_config_);
    }

    // optional .object_detection.protos.GraphRewriter graph_rewriter = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *graph_rewriter_);
    }

  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TrainEvalPipelineConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:object_detection.protos.TrainEvalPipelineConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const TrainEvalPipelineConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TrainEvalPipelineConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:object_detection.protos.TrainEvalPipelineConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:object_detection.protos.TrainEvalPipelineConfig)
    MergeFrom(*source);
  }
}

void TrainEvalPipelineConfig::MergeFrom(const TrainEvalPipelineConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:object_detection.protos.TrainEvalPipelineConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _extensions_.MergeFrom(from._extensions_);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  eval_input_reader_.MergeFrom(from.eval_input_reader_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      mutable_model()->::object_detection::protos::DetectionModel::MergeFrom(from.model());
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_train_config()->::object_detection::protos::TrainConfig::MergeFrom(from.train_config());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_train_input_reader()->::object_detection::protos::InputReader::MergeFrom(from.train_input_reader());
    }
    if (cached_has_bits & 0x00000008u) {
      mutable_eval_config()->::object_detection::protos::EvalConfig::MergeFrom(from.eval_config());
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_graph_rewriter()->::object_detection::protos::GraphRewriter::MergeFrom(from.graph_rewriter());
    }
  }
}

void TrainEvalPipelineConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:object_detection.protos.TrainEvalPipelineConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrainEvalPipelineConfig::CopyFrom(const TrainEvalPipelineConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:object_detection.protos.TrainEvalPipelineConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrainEvalPipelineConfig::IsInitialized() const {
  if (!_extensions_.IsInitialized()) {
    return false;
  }

  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(this->eval_input_reader())) return false;
  if (has_train_input_reader()) {
    if (!this->train_input_reader_->IsInitialized()) return false;
  }
  if (has_graph_rewriter()) {
    if (!this->graph_rewriter_->IsInitialized()) return false;
  }
  return true;
}

void TrainEvalPipelineConfig::InternalSwap(TrainEvalPipelineConfig* other) {
  using std::swap;
  _extensions_.Swap(&other->_extensions_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  CastToBase(&eval_input_reader_)->InternalSwap(CastToBase(&other->eval_input_reader_));
  swap(model_, other->model_);
  swap(train_config_, other->train_config_);
  swap(train_input_reader_, other->train_input_reader_);
  swap(eval_config_, other->eval_config_);
  swap(graph_rewriter_, other->graph_rewriter_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TrainEvalPipelineConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::object_detection::protos::TrainEvalPipelineConfig* Arena::CreateMaybeMessage< ::object_detection::protos::TrainEvalPipelineConfig >(Arena* arena) {
  return Arena::CreateInternal< ::object_detection::protos::TrainEvalPipelineConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
